export const weatherIcons = {
  '01d': require('../../assets/img/weather/01d.png'),
  '02d': require('../../assets/img/weather/02d.png'),
  '03d': require('../../assets/img/weather/03d.png'),
  '04d': require('../../assets/img/weather/04d.png'),
  '09d': require('../../assets/img/weather/09d.png'),
  '10d': require('../../assets/img/weather/10d.png'),
  '11d': require('../../assets/img/weather/11d.png'),
  '13d': require('../../assets/img/weather/13d.png'),
  '50d': require('../../assets/img/weather/50d.png'),
  '01n': require('../../assets/img/weather/01n.png'),
  '02n': require('../../assets/img/weather/02n.png'),
  '03n': require('../../assets/img/weather/03n.png'),
  '04n': require('../../assets/img/weather/04n.png'),
  '09n': require('../../assets/img/weather/09n.png'),
  '10n': require('../../assets/img/weather/10n.png'),
  '11n': require('../../assets/img/weather/11n.png'),
  '13n': require('../../assets/img/weather/13n.png'),
  '50n': require('../../assets/img/weather/50n.png'),
};
